language: python
cache:
  directories:
    - $HOME/.ccache
sudo: false
before_install:
  - "./tools/install_travis.sh"
install: "source $TRAVIS_BUILD_DIR/source"
script: "source $TRAVIS_BUILD_DIR/source"
